### ISSUE TITLE
Base import not included by default

### ISSUE THREAD

**Issue by michael-dev-pilotin** [Pilot-in/PiloPress-Addon#14]
/TailwindCSS/CSS 

Base Import Toggle look like **active** in back-office, but value is not properly saved.

Temporary Fix: Disable / Enable toggle, save and compile

**Comment by damien-pilot-in** [comment]
- Need to change system used `load_value` and swap to `update_field`.
- Need default style should be:
```css
body {
    max-width: 100vw;
}

button:focus {
    outline: none;
}

ul:not([class]) {
    @apply list-disc list-inside;
}

ol:not([class]) {
    @apply list-decimal list-inside;
}

ul[class],
ol[class] {
    @apply list-none;
}

/** Images */
picture {
    @apply block align-middle;

    & > img {
        all: inherit;
    }

    /** Fix when img are replaced with picture */
    &:not([class*="wp-image"]) > img {
        @apply w-full h-full object-cover;
    }
}

/* Inputs */
input[type="email"],
input[type="password"],
input[type="text"],
input[type="tel"],
input[type="number"],
select,
textarea,
.select2 > .selection > .select2-selection {
    @apply h-auto text-sm border-2 border-gray-500 rounded p-3 !important;
}

/* Select2 - Fix margin */
.select2 > .selection > .select2-selection {
    @apply m-0 !important;
}

/* Select2 - Fix arrow position */
.select2 > .selection > .select2-selection > .select2-selection__arrow {
    top: 50%;
    right: 1%;
    transform: translateY(-50%);
}

/* Select2 - Fix clear icon position */
.select2 > .selection .select2-selection__clear {
    @apply px-2 py-0 !important;
    margin-right: calc(1% + 1em) !important;
}

/* Select2 - Fix select style */
.select2 > .selection > .select2-selection > .select2-selection__rendered {
    @apply p-0 !important;
    line-height: inherit !important;
}

/** Select2 - Dropdown - Option selected - Hover */
.select2-results > .select2-results__options > .select2-results__option--highlighted[aria-selected],
.select2-results > .select2-results__options > .select2-results__option--highlighted[data-selected] {
    /* @apply bg-secondary !important; */
}

/** WYSIWYG alignment styles */
.aligncenter {
    @apply mx-auto;
}

.alignleft {
    @apply mr-auto;
}

.alignright {
    @apply ml-auto;
}

/* Pagination */
.pagination {
    @apply flex items-center justify-center text-black w-full pt-6 border-t border-gray-500;

    .page-numbers {
        @apply px-1 mr-1;
    }

    /* Hover, current */
    .page-numbers.current,
    .prev:hover,
    .next:hover {
        @apply text-primary;
    }
}

/**
* Button basic styling
* (extend it to create your buttons)
*/
.btn-base {
    @apply relative inline-flex items-center justify-center text-sm text-black uppercase;
    @apply px-4 py-2 leading-none font-primary font-bold bg-gray border-2 border-solid border-gray mr-2 mb-2;
}

/** Icon Font Awesome - Left position */
.icon-left {
    &::before {
        content: "";
        display: inline-block;
        font-family: "Font Awesome 5 Pro";
        font-weight: 400;
        color: currentcolor;
        margin-right: 12px;
        text-align: center;
    }
}

/** Icon Font Awesome - Right position */
.icon-right {
    &::after {
        content: "";
        display: inline-block;
        font-family: "Font Awesome 5 Pro";
        font-weight: 400;
        color: currentcolor;
        margin-left: 12px;
        text-align: center;
    }
}

/** Blockquote */
blockquote {
    @apply border-l-4 border-primary px-16 my-16 ml-6 text-primary text-2xl leading-9;
}

/** ----------------------------------
* Put your custom styles here below...
* ---------------------------------- */

```
