### ISSUE TITLE
Enhance visually disabled layouts in post edition

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress-Addon#22]
Something like that:   

![image](https://user-images.githubusercontent.com/62112531/117972618-a5b4fe80-b32b-11eb-8019-27e32ee24b01.png)

```css
.layout.acfe-flexible-layout-hidden>.acfe-fc-placeholder {
  filter: grayscale(1);
  opacity: 0.9;
  background: repeating-linear-gradient( -45deg, #0d0f31, #0d0f31 5px, #f9f9fd 5px, #f9f9fd 25px );
}
```
